INSERT INTO employee VALUES(1, 'Courtnay', 'Mitzi', 'Tbilisi', 'Senegal', 'VI', '2004-09-18');
INSERT INTO employee VALUES(2, 'Yvonne', 'Blisse', 'Belfast', 'Saint Helena', 'NO', '2006-11-18');
INSERT INTO employee VALUES(3, 'Arabel', 'Dyche', 'Niamey', 'Cayman Islands', 'SY', '1998-03-29');
INSERT INTO employee VALUES(4, 'Fidelia', 'Germann', 'Daegu', 'Montserrat', 'EE', '1999-08-21');
INSERT INTO employee VALUES(5, 'Kara-Lynn', 'Tristram', 'Reykjavík', 'Djibouti', 'AW', '1975-04-23');
INSERT INTO employee VALUES(6, 'Caressa', 'Blisse', 'Yokohama', 'Cayman Islands', 'PN', '1973-11-07');
INSERT INTO employee VALUES(7, 'Philis', 'Amand', 'Port Hedland', 'Anguilla', 'PE', '1972-05-08');
INSERT INTO employee VALUES(8, 'Kial', 'Karylin', 'Houston', 'Angola', 'SD', '1980-05-02');
INSERT INTO employee VALUES(9, 'Korrie', 'Donell', 'Medan', 'Iraq', 'PG', '1970-09-24');
INSERT INTO employee VALUES(10, 'Rosanne', 'Shields', 'Raleigh', 'Togo', 'SY', '2001-10-21');
INSERT INTO employee VALUES(11, 'Dede', 'Berard', 'Toronto', 'Japan', 'IS', '1997-07-28');
INSERT INTO employee VALUES(12, 'Margarette', 'Wattenberg', 'Baku', 'Tokelau', 'MY', '1995-10-11');
INSERT INTO employee VALUES(13, 'Lucy', 'Hedve', 'Ankara', 'Gabon', 'VI', '1999-11-16');
INSERT INTO employee VALUES(14, 'Felice', 'Sherrie', 'Nizhny Novgorod', 'Peru', 'CH', '2000-10-18');
INSERT INTO employee VALUES(15, 'Angelique', 'Mayeda', 'Ürümqi', 'Senegal', 'QA', '1970-10-21');
INSERT INTO employee VALUES(16, 'Lindie', 'Ethban', 'Dar es Salaam', 'Armenia', 'JP', '2017-06-04');
INSERT INTO employee VALUES(17, 'Alejandra', 'Read', 'Dushanbe', 'Montserrat', 'SO', '1996-10-24');
INSERT INTO employee VALUES(18, 'Jordan', 'Sacken', 'Lviv', 'Eritrea', 'NU', '1970-10-16');
INSERT INTO employee VALUES(19, 'Maridel', 'McCutcheon', 'Odessa', 'Lao People''S Democratic Republic', 'BW', '1980-11-23');
INSERT INTO employee VALUES(20, 'Blinni', 'Reinke', 'Cannes', 'Saint Lucia', 'CH', '2018-07-27');
INSERT INTO employee VALUES(21, 'Ana', 'Guildroy', 'Philadelphia', 'Tonga', 'SB', '2002-02-17');
INSERT INTO employee VALUES(22, 'Consuela', 'Saree', 'Road Town', 'Nauru', 'PL', '2019-06-04');
INSERT INTO employee VALUES(23, 'Carmela', 'Fredi', 'Avarua', 'Malaysia', 'FI', '2005-06-17');
INSERT INTO employee VALUES(24, 'Emelina', 'Fiester', 'Padang', 'Saint Lucia', 'ET', '2014-06-04');
INSERT INTO employee VALUES(25, 'Chastity', 'Jerald', 'Castries', 'Guinea', 'IL', '2013-02-08');
INSERT INTO employee VALUES(26, 'Maridel', 'Giule', 'Shillong', 'Azerbaijan', 'BN', '2005-06-14');
INSERT INTO employee VALUES(27, 'Alameda', 'Salvidor', 'Hong Kong', 'Hungary', 'VN', '2014-12-06');
INSERT INTO employee VALUES(28, 'Gisela', 'Ingra', 'Ilhéus', 'American Samoa', 'HM', '2000-06-29');
INSERT INTO employee VALUES(29, 'Shel', 'Brian', 'Ulan Bator', 'Greece', 'IS', '2003-06-01');
INSERT INTO employee VALUES(30, 'Lesly', 'Creamer', 'Guatemala City', 'Czech Republic', 'DO', '1984-03-31');
INSERT INTO employee VALUES(31, 'Fina', 'Letsou', 'N''Djamena', 'El Salvador', 'MW', '2014-12-31');
INSERT INTO employee VALUES(32, 'Esmeralda', 'Candy', 'Kharkiv', 'Western Sahara', 'EG', '2014-10-22');
INSERT INTO employee VALUES(33, 'Talya', 'Yorick', 'Kandahar', 'Suriname', 'TO', '1995-06-13');
INSERT INTO employee VALUES(34, 'Shaylyn', 'Chem', 'Jersey City', 'Monaco', 'MH', '1991-12-11');
INSERT INTO employee VALUES(35, 'Sindee', 'Madaih', 'Nouakchott', 'New Zealand', 'ST', '1983-06-28');
INSERT INTO employee VALUES(36, 'Marcelline', 'Zamora', 'Batticaloa', 'Macedonia, The Former Yugoslav Republic of', 'DJ', '2019-02-24');
INSERT INTO employee VALUES(37, 'Sallie', 'Zamora', 'Surat Thani', 'Bahamas', 'AR', '2002-03-28');
INSERT INTO employee VALUES(38, 'Jobi', 'Guthrie', 'Kuching', 'Norfolk Island', 'IR', '2013-06-20');
INSERT INTO employee VALUES(39, 'Bernardine', 'Peti', 'Dibrugarh', 'Nepal', 'TG', '1982-06-12');
INSERT INTO employee VALUES(40, 'Mariele', 'Dex', 'Vancouver', 'Cayman Islands', 'KY', '2009-07-22');
